//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LitJson_JsonMapperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LitJson.JsonMapper), typeof(System.Object));
		L.RegFunction("ToJson", ToJson);
		L.RegFunction("ToObject", ToObject);
		L.RegFunction("ToWrapper", ToWrapper);
		L.RegFunction("UnregisterExporters", UnregisterExporters);
		L.RegFunction("UnregisterImporters", UnregisterImporters);
		L.RegFunction("New", _CreateLitJson_JsonMapper);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLitJson_JsonMapper(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LitJson.JsonMapper obj = new LitJson.JsonMapper();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LitJson.JsonMapper.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToJson(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				object arg0 = ToLua.ToVarObject(L, 1);
				string o = LitJson.JsonMapper.ToJson(arg0);
				LuaDLL.lua_pushstring(L, o);
				return 1;
			}
			else if (count == 2)
			{
				object arg0 = ToLua.ToVarObject(L, 1);
				LitJson.JsonWriter arg1 = (LitJson.JsonWriter)ToLua.CheckObject<LitJson.JsonWriter>(L, 2);
				LitJson.JsonMapper.ToJson(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LitJson.JsonMapper.ToJson");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToObject(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1 && TypeChecker.CheckTypes<LitJson.JsonReader>(L, 1))
			{
				LitJson.JsonReader arg0 = (LitJson.JsonReader)ToLua.ToObject(L, 1);
				LitJson.JsonData o = LitJson.JsonMapper.ToObject(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<System.IO.TextReader>(L, 1))
			{
				System.IO.TextReader arg0 = (System.IO.TextReader)ToLua.ToObject(L, 1);
				LitJson.JsonData o = LitJson.JsonMapper.ToObject(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 1 && TypeChecker.CheckTypes<string>(L, 1))
			{
				string arg0 = ToLua.ToString(L, 1);
				LitJson.JsonData o = LitJson.JsonMapper.ToObject(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2)
			{
				string arg0 = ToLua.CheckString(L, 1);
				System.Type arg1 = ToLua.CheckMonoType(L, 2);
				object o = LitJson.JsonMapper.ToObject(arg0, arg1);
				ToLua.Push(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LitJson.JsonMapper.ToObject");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToWrapper(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<LitJson.JsonReader>(L, 2))
			{
				LitJson.WrapperFactory arg0 = (LitJson.WrapperFactory)ToLua.CheckDelegate<LitJson.WrapperFactory>(L, 1);
				LitJson.JsonReader arg1 = (LitJson.JsonReader)ToLua.ToObject(L, 2);
				LitJson.IJsonWrapper o = LitJson.JsonMapper.ToWrapper(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				LitJson.WrapperFactory arg0 = (LitJson.WrapperFactory)ToLua.CheckDelegate<LitJson.WrapperFactory>(L, 1);
				string arg1 = ToLua.ToString(L, 2);
				LitJson.IJsonWrapper o = LitJson.JsonMapper.ToWrapper(arg0, arg1);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: LitJson.JsonMapper.ToWrapper");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnregisterExporters(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			LitJson.JsonMapper.UnregisterExporters();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnregisterImporters(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			LitJson.JsonMapper.UnregisterImporters();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

