//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LoadingManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LoadingManager), typeof(MonoSingleton<LoadingManager>));
		L.RegFunction("SetProgressText", SetProgressText);
		L.RegFunction("SetProgressSliderValue", SetProgressSliderValue);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetProgressText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LoadingManager obj = (LoadingManager)ToLua.CheckObject<LoadingManager>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.SetProgressText(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetProgressSliderValue(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LoadingManager obj = (LoadingManager)ToLua.CheckObject<LoadingManager>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.SetProgressSliderValue(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

