// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/MsgAds.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace QiLieGuaner {

  /// <summary>Holder for reflection information generated from Proto/MsgAds.proto</summary>
  public static partial class MsgAdsReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/MsgAds.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgAdsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJQcm90by9Nc2dBZHMucHJvdG8SC1FpTGllR3VhbmVyInEKGlVuaXR5QWRz",
            "V2F0Y2hGaW5pc2hSZXF1ZXN0EhIKCnBsYXllckdVSUQYASABKAUSEwoLcGxh",
            "Y2VtZW50SWQYAiABKAkSKgoGcmVzdWx0GAMgASgOMhouUWlMaWVHdWFuZXIu",
            "QWRzU2hvd1Jlc3VsdCJHChpVbml0eUFkc1dhdGNoRmluaXNoUmVjZWl2ZRIS",
            "CgpwbGF5ZXJHVUlEGAEgASgFEhUKDWdvbGRDb2luQ291bnQYAiABKAUqNgoN",
            "QWRzU2hvd1Jlc3VsdBIKCgZGYWlsZWQQABILCgdTa2lwcGVkEAESDAoIRmlu",
            "aXNoZWQQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::QiLieGuaner.AdsShowResult), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::QiLieGuaner.UnityAdsWatchFinishRequest), global::QiLieGuaner.UnityAdsWatchFinishRequest.Parser, new[]{ "PlayerGUID", "PlacementId", "Result" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QiLieGuaner.UnityAdsWatchFinishReceive), global::QiLieGuaner.UnityAdsWatchFinishReceive.Parser, new[]{ "PlayerGUID", "GoldCoinCount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///广告观看结果
  /// </summary>
  public enum AdsShowResult {
    /// <summary>
    ///广告观看失败
    /// </summary>
    [pbr::OriginalName("Failed")] Failed = 0,
    /// <summary>
    ///广告被跳过
    /// </summary>
    [pbr::OriginalName("Skipped")] Skipped = 1,
    /// <summary>
    ///广告观看完成
    /// </summary>
    [pbr::OriginalName("Finished")] Finished = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  ///Unity广告观看完成请求
  /// </summary>
  public sealed partial class UnityAdsWatchFinishRequest : pb::IMessage<UnityAdsWatchFinishRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UnityAdsWatchFinishRequest> _parser = new pb::MessageParser<UnityAdsWatchFinishRequest>(() => new UnityAdsWatchFinishRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityAdsWatchFinishRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QiLieGuaner.MsgAdsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityAdsWatchFinishRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityAdsWatchFinishRequest(UnityAdsWatchFinishRequest other) : this() {
      playerGUID_ = other.playerGUID_;
      placementId_ = other.placementId_;
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityAdsWatchFinishRequest Clone() {
      return new UnityAdsWatchFinishRequest(this);
    }

    /// <summary>Field number for the "playerGUID" field.</summary>
    public const int PlayerGUIDFieldNumber = 1;
    private int playerGUID_;
    /// <summary>
    ///玩家GUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerGUID {
      get { return playerGUID_; }
      set {
        playerGUID_ = value;
      }
    }

    /// <summary>Field number for the "placementId" field.</summary>
    public const int PlacementIdFieldNumber = 2;
    private string placementId_ = "";
    /// <summary>
    ///广告ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PlacementId {
      get { return placementId_; }
      set {
        placementId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 3;
    private global::QiLieGuaner.AdsShowResult result_ = global::QiLieGuaner.AdsShowResult.Failed;
    /// <summary>
    ///广告观看结果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QiLieGuaner.AdsShowResult Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityAdsWatchFinishRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityAdsWatchFinishRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerGUID != other.PlayerGUID) return false;
      if (PlacementId != other.PlacementId) return false;
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerGUID != 0) hash ^= PlayerGUID.GetHashCode();
      if (PlacementId.Length != 0) hash ^= PlacementId.GetHashCode();
      if (Result != global::QiLieGuaner.AdsShowResult.Failed) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (PlacementId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PlacementId);
      }
      if (Result != global::QiLieGuaner.AdsShowResult.Failed) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (PlacementId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PlacementId);
      }
      if (Result != global::QiLieGuaner.AdsShowResult.Failed) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerGUID);
      }
      if (PlacementId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlacementId);
      }
      if (Result != global::QiLieGuaner.AdsShowResult.Failed) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityAdsWatchFinishRequest other) {
      if (other == null) {
        return;
      }
      if (other.PlayerGUID != 0) {
        PlayerGUID = other.PlayerGUID;
      }
      if (other.PlacementId.Length != 0) {
        PlacementId = other.PlacementId;
      }
      if (other.Result != global::QiLieGuaner.AdsShowResult.Failed) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 18: {
            PlacementId = input.ReadString();
            break;
          }
          case 24: {
            Result = (global::QiLieGuaner.AdsShowResult) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 18: {
            PlacementId = input.ReadString();
            break;
          }
          case 24: {
            Result = (global::QiLieGuaner.AdsShowResult) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///Unity广告观看完成响应
  /// </summary>
  public sealed partial class UnityAdsWatchFinishReceive : pb::IMessage<UnityAdsWatchFinishReceive>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UnityAdsWatchFinishReceive> _parser = new pb::MessageParser<UnityAdsWatchFinishReceive>(() => new UnityAdsWatchFinishReceive());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityAdsWatchFinishReceive> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QiLieGuaner.MsgAdsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityAdsWatchFinishReceive() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityAdsWatchFinishReceive(UnityAdsWatchFinishReceive other) : this() {
      playerGUID_ = other.playerGUID_;
      goldCoinCount_ = other.goldCoinCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityAdsWatchFinishReceive Clone() {
      return new UnityAdsWatchFinishReceive(this);
    }

    /// <summary>Field number for the "playerGUID" field.</summary>
    public const int PlayerGUIDFieldNumber = 1;
    private int playerGUID_;
    /// <summary>
    ///玩家GUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerGUID {
      get { return playerGUID_; }
      set {
        playerGUID_ = value;
      }
    }

    /// <summary>Field number for the "goldCoinCount" field.</summary>
    public const int GoldCoinCountFieldNumber = 2;
    private int goldCoinCount_;
    /// <summary>
    ///当前玩家的金币数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoldCoinCount {
      get { return goldCoinCount_; }
      set {
        goldCoinCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityAdsWatchFinishReceive);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityAdsWatchFinishReceive other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerGUID != other.PlayerGUID) return false;
      if (GoldCoinCount != other.GoldCoinCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerGUID != 0) hash ^= PlayerGUID.GetHashCode();
      if (GoldCoinCount != 0) hash ^= GoldCoinCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (GoldCoinCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoldCoinCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (GoldCoinCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoldCoinCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerGUID);
      }
      if (GoldCoinCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoldCoinCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityAdsWatchFinishReceive other) {
      if (other == null) {
        return;
      }
      if (other.PlayerGUID != 0) {
        PlayerGUID = other.PlayerGUID;
      }
      if (other.GoldCoinCount != 0) {
        GoldCoinCount = other.GoldCoinCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            GoldCoinCount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            GoldCoinCount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
