// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/MsgMall.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace QiLieGuaner {

  /// <summary>Holder for reflection information generated from Proto/MsgMall.proto</summary>
  public static partial class MsgMallReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/MsgMall.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgMallReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQcm90by9Nc2dNYWxsLnByb3RvEgtRaUxpZUd1YW5lciJXChBNYWxsR29v",
            "ZHNSZXF1ZXN0EhIKCnBsYXllckdVSUQYASABKAUSLwoPc2VsZWN0R29vZHNU",
            "eXBlGAIgASgOMhYuUWlMaWVHdWFuZXIuR29vZHNUeXBlImcKEE1hbGxHb29k",
            "c1JlY2VpdmUSEgoKcGxheWVyR1VJRBgBIAEoBRIvCg9zZWxlY3RHb29kc1R5",
            "cGUYAiABKA4yFi5RaUxpZUd1YW5lci5Hb29kc1R5cGUSDgoGcmVzdWx0GAMg",
            "AygJIk8KGEFkZFRvU2hvcHBpbmdDYXJkUmVxdWVzdBISCgpwbGF5ZXJHVUlE",
            "GAEgASgFEg8KB2dvb2RzSUQYAiABKAUSDgoGYW1vdW50GAMgASgFIjoKGEFk",
            "ZFRvU2hvcHBpbmdDYXJkUmVjZWl2ZRINCgVzdGF0ZRgBIAEoBRIPCgdnb29k",
            "c0lEGAIgASgFIikKE1Nob3BwaW5nQ2FyZFJlcXVlc3QSEgoKcGxheWVyR1VJ",
            "RBgBIAEoBSI5ChNTaG9wcGluZ0NhcmRSZWNlaXZlEhIKCnBsYXllckdVSUQY",
            "ASABKAUSDgoGcmVzdWx0GAIgAygJIukBCiRVcGRhdGVTaG9wcGluZ0NhcmRH",
            "b29kc0Ftb3VudFJlcXVlc3QSEgoKcGxheWVyR1VJRBgBIAEoBRJWCgp1cGRh",
            "dGVUeXBlGAIgASgOMkIuUWlMaWVHdWFuZXIuVXBkYXRlU2hvcHBpbmdDYXJk",
            "R29vZHNBbW91bnRSZXF1ZXN0LlVwZGF0ZUFtb3VudFR5cGUSDwoHZ29vZHNJ",
            "RBgDIAEoBRIWCg5nb29kc0FkZEFtb3VudBgEIAEoBSIsChBVcGRhdGVBbW91",
            "bnRUeXBlEgwKCEluY3JlYXNlEAASCgoGUmVkdWNlEAEiYAokVXBkYXRlU2hv",
            "cHBpbmdDYXJkR29vZHNBbW91bnRSZWNlaXZlEhIKCnBsYXllckdVSUQYASAB",
            "KAUSDwoHZ29vZHNJRBgCIAEoBRITCgtnb29kc0Ftb3VudBgDIAEoBSInChFT",
            "ZXR0bGVtZW50UmVxdWVzdBISCgpwbGF5ZXJHVUlEGAEgASgFIjYKEVNldHRs",
            "ZW1lbnRSZWNlaXZlEhIKCnBsYXllckdVSUQYASABKAUSDQoFc3RhdGUYAiAB",
            "KAUqIwoJR29vZHNUeXBlEggKBEl0ZW0QABIMCghHb2xkQ29pbhABYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::QiLieGuaner.GoodsType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::QiLieGuaner.MallGoodsRequest), global::QiLieGuaner.MallGoodsRequest.Parser, new[]{ "PlayerGUID", "SelectGoodsType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QiLieGuaner.MallGoodsReceive), global::QiLieGuaner.MallGoodsReceive.Parser, new[]{ "PlayerGUID", "SelectGoodsType", "Result" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QiLieGuaner.AddToShoppingCardRequest), global::QiLieGuaner.AddToShoppingCardRequest.Parser, new[]{ "PlayerGUID", "GoodsID", "Amount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QiLieGuaner.AddToShoppingCardReceive), global::QiLieGuaner.AddToShoppingCardReceive.Parser, new[]{ "State", "GoodsID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QiLieGuaner.ShoppingCardRequest), global::QiLieGuaner.ShoppingCardRequest.Parser, new[]{ "PlayerGUID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QiLieGuaner.ShoppingCardReceive), global::QiLieGuaner.ShoppingCardReceive.Parser, new[]{ "PlayerGUID", "Result" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest), global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest.Parser, new[]{ "PlayerGUID", "UpdateType", "GoodsID", "GoodsAddAmount" }, null, new[]{ typeof(global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest.Types.UpdateAmountType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QiLieGuaner.UpdateShoppingCardGoodsAmountReceive), global::QiLieGuaner.UpdateShoppingCardGoodsAmountReceive.Parser, new[]{ "PlayerGUID", "GoodsID", "GoodsAmount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QiLieGuaner.SettlementRequest), global::QiLieGuaner.SettlementRequest.Parser, new[]{ "PlayerGUID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QiLieGuaner.SettlementReceive), global::QiLieGuaner.SettlementReceive.Parser, new[]{ "PlayerGUID", "State" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///商品的类型
  /// </summary>
  public enum GoodsType {
    /// <summary>
    ///用游戏内货币购买的商品
    /// </summary>
    [pbr::OriginalName("Item")] Item = 0,
    /// <summary>
    ///用现实货币购买游戏内货币
    /// </summary>
    [pbr::OriginalName("GoldCoin")] GoldCoin = 1,
  }

  #endregion

  #region Messages
  /// <summary>
  ///商城商品列表请求
  /// </summary>
  public sealed partial class MallGoodsRequest : pb::IMessage<MallGoodsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MallGoodsRequest> _parser = new pb::MessageParser<MallGoodsRequest>(() => new MallGoodsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MallGoodsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QiLieGuaner.MsgMallReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MallGoodsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MallGoodsRequest(MallGoodsRequest other) : this() {
      playerGUID_ = other.playerGUID_;
      selectGoodsType_ = other.selectGoodsType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MallGoodsRequest Clone() {
      return new MallGoodsRequest(this);
    }

    /// <summary>Field number for the "playerGUID" field.</summary>
    public const int PlayerGUIDFieldNumber = 1;
    private int playerGUID_;
    /// <summary>
    ///玩家GUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerGUID {
      get { return playerGUID_; }
      set {
        playerGUID_ = value;
      }
    }

    /// <summary>Field number for the "selectGoodsType" field.</summary>
    public const int SelectGoodsTypeFieldNumber = 2;
    private global::QiLieGuaner.GoodsType selectGoodsType_ = global::QiLieGuaner.GoodsType.Item;
    /// <summary>
    ///查询什么类型的商品
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QiLieGuaner.GoodsType SelectGoodsType {
      get { return selectGoodsType_; }
      set {
        selectGoodsType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MallGoodsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MallGoodsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerGUID != other.PlayerGUID) return false;
      if (SelectGoodsType != other.SelectGoodsType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerGUID != 0) hash ^= PlayerGUID.GetHashCode();
      if (SelectGoodsType != global::QiLieGuaner.GoodsType.Item) hash ^= SelectGoodsType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (SelectGoodsType != global::QiLieGuaner.GoodsType.Item) {
        output.WriteRawTag(16);
        output.WriteEnum((int) SelectGoodsType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (SelectGoodsType != global::QiLieGuaner.GoodsType.Item) {
        output.WriteRawTag(16);
        output.WriteEnum((int) SelectGoodsType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerGUID);
      }
      if (SelectGoodsType != global::QiLieGuaner.GoodsType.Item) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SelectGoodsType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MallGoodsRequest other) {
      if (other == null) {
        return;
      }
      if (other.PlayerGUID != 0) {
        PlayerGUID = other.PlayerGUID;
      }
      if (other.SelectGoodsType != global::QiLieGuaner.GoodsType.Item) {
        SelectGoodsType = other.SelectGoodsType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            SelectGoodsType = (global::QiLieGuaner.GoodsType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            SelectGoodsType = (global::QiLieGuaner.GoodsType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///商城商品列表响应
  /// </summary>
  public sealed partial class MallGoodsReceive : pb::IMessage<MallGoodsReceive>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MallGoodsReceive> _parser = new pb::MessageParser<MallGoodsReceive>(() => new MallGoodsReceive());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MallGoodsReceive> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QiLieGuaner.MsgMallReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MallGoodsReceive() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MallGoodsReceive(MallGoodsReceive other) : this() {
      playerGUID_ = other.playerGUID_;
      selectGoodsType_ = other.selectGoodsType_;
      result_ = other.result_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MallGoodsReceive Clone() {
      return new MallGoodsReceive(this);
    }

    /// <summary>Field number for the "playerGUID" field.</summary>
    public const int PlayerGUIDFieldNumber = 1;
    private int playerGUID_;
    /// <summary>
    ///查询的玩家GUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerGUID {
      get { return playerGUID_; }
      set {
        playerGUID_ = value;
      }
    }

    /// <summary>Field number for the "selectGoodsType" field.</summary>
    public const int SelectGoodsTypeFieldNumber = 2;
    private global::QiLieGuaner.GoodsType selectGoodsType_ = global::QiLieGuaner.GoodsType.Item;
    /// <summary>
    ///查询什么类型的商品
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QiLieGuaner.GoodsType SelectGoodsType {
      get { return selectGoodsType_; }
      set {
        selectGoodsType_ = value;
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_result_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> result_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///商品查询结果。每项之间用‘|’分隔
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Result {
      get { return result_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MallGoodsReceive);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MallGoodsReceive other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerGUID != other.PlayerGUID) return false;
      if (SelectGoodsType != other.SelectGoodsType) return false;
      if(!result_.Equals(other.result_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerGUID != 0) hash ^= PlayerGUID.GetHashCode();
      if (SelectGoodsType != global::QiLieGuaner.GoodsType.Item) hash ^= SelectGoodsType.GetHashCode();
      hash ^= result_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (SelectGoodsType != global::QiLieGuaner.GoodsType.Item) {
        output.WriteRawTag(16);
        output.WriteEnum((int) SelectGoodsType);
      }
      result_.WriteTo(output, _repeated_result_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (SelectGoodsType != global::QiLieGuaner.GoodsType.Item) {
        output.WriteRawTag(16);
        output.WriteEnum((int) SelectGoodsType);
      }
      result_.WriteTo(ref output, _repeated_result_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerGUID);
      }
      if (SelectGoodsType != global::QiLieGuaner.GoodsType.Item) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SelectGoodsType);
      }
      size += result_.CalculateSize(_repeated_result_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MallGoodsReceive other) {
      if (other == null) {
        return;
      }
      if (other.PlayerGUID != 0) {
        PlayerGUID = other.PlayerGUID;
      }
      if (other.SelectGoodsType != global::QiLieGuaner.GoodsType.Item) {
        SelectGoodsType = other.SelectGoodsType;
      }
      result_.Add(other.result_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            SelectGoodsType = (global::QiLieGuaner.GoodsType) input.ReadEnum();
            break;
          }
          case 26: {
            result_.AddEntriesFrom(input, _repeated_result_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            SelectGoodsType = (global::QiLieGuaner.GoodsType) input.ReadEnum();
            break;
          }
          case 26: {
            result_.AddEntriesFrom(ref input, _repeated_result_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///添加到购物车请求
  /// </summary>
  public sealed partial class AddToShoppingCardRequest : pb::IMessage<AddToShoppingCardRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AddToShoppingCardRequest> _parser = new pb::MessageParser<AddToShoppingCardRequest>(() => new AddToShoppingCardRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddToShoppingCardRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QiLieGuaner.MsgMallReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddToShoppingCardRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddToShoppingCardRequest(AddToShoppingCardRequest other) : this() {
      playerGUID_ = other.playerGUID_;
      goodsID_ = other.goodsID_;
      amount_ = other.amount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddToShoppingCardRequest Clone() {
      return new AddToShoppingCardRequest(this);
    }

    /// <summary>Field number for the "playerGUID" field.</summary>
    public const int PlayerGUIDFieldNumber = 1;
    private int playerGUID_;
    /// <summary>
    ///玩家GUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerGUID {
      get { return playerGUID_; }
      set {
        playerGUID_ = value;
      }
    }

    /// <summary>Field number for the "goodsID" field.</summary>
    public const int GoodsIDFieldNumber = 2;
    private int goodsID_;
    /// <summary>
    ///商品ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoodsID {
      get { return goodsID_; }
      set {
        goodsID_ = value;
      }
    }

    /// <summary>Field number for the "amount" field.</summary>
    public const int AmountFieldNumber = 3;
    private int amount_;
    /// <summary>
    ///添加数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Amount {
      get { return amount_; }
      set {
        amount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddToShoppingCardRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddToShoppingCardRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerGUID != other.PlayerGUID) return false;
      if (GoodsID != other.GoodsID) return false;
      if (Amount != other.Amount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerGUID != 0) hash ^= PlayerGUID.GetHashCode();
      if (GoodsID != 0) hash ^= GoodsID.GetHashCode();
      if (Amount != 0) hash ^= Amount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (GoodsID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoodsID);
      }
      if (Amount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (GoodsID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoodsID);
      }
      if (Amount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerGUID);
      }
      if (GoodsID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodsID);
      }
      if (Amount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Amount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddToShoppingCardRequest other) {
      if (other == null) {
        return;
      }
      if (other.PlayerGUID != 0) {
        PlayerGUID = other.PlayerGUID;
      }
      if (other.GoodsID != 0) {
        GoodsID = other.GoodsID;
      }
      if (other.Amount != 0) {
        Amount = other.Amount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            GoodsID = input.ReadInt32();
            break;
          }
          case 24: {
            Amount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            GoodsID = input.ReadInt32();
            break;
          }
          case 24: {
            Amount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///添加到购物车响应
  /// </summary>
  public sealed partial class AddToShoppingCardReceive : pb::IMessage<AddToShoppingCardReceive>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AddToShoppingCardReceive> _parser = new pb::MessageParser<AddToShoppingCardReceive>(() => new AddToShoppingCardReceive());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddToShoppingCardReceive> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QiLieGuaner.MsgMallReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddToShoppingCardReceive() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddToShoppingCardReceive(AddToShoppingCardReceive other) : this() {
      state_ = other.state_;
      goodsID_ = other.goodsID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddToShoppingCardReceive Clone() {
      return new AddToShoppingCardReceive(this);
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 1;
    private int state_;
    /// <summary>
    ///添加结果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "goodsID" field.</summary>
    public const int GoodsIDFieldNumber = 2;
    private int goodsID_;
    /// <summary>
    ///商品ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoodsID {
      get { return goodsID_; }
      set {
        goodsID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddToShoppingCardReceive);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddToShoppingCardReceive other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (State != other.State) return false;
      if (GoodsID != other.GoodsID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (State != 0) hash ^= State.GetHashCode();
      if (GoodsID != 0) hash ^= GoodsID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (State != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(State);
      }
      if (GoodsID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoodsID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (State != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(State);
      }
      if (GoodsID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoodsID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(State);
      }
      if (GoodsID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodsID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddToShoppingCardReceive other) {
      if (other == null) {
        return;
      }
      if (other.State != 0) {
        State = other.State;
      }
      if (other.GoodsID != 0) {
        GoodsID = other.GoodsID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            State = input.ReadInt32();
            break;
          }
          case 16: {
            GoodsID = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            State = input.ReadInt32();
            break;
          }
          case 16: {
            GoodsID = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///购物车列表请求
  /// </summary>
  public sealed partial class ShoppingCardRequest : pb::IMessage<ShoppingCardRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ShoppingCardRequest> _parser = new pb::MessageParser<ShoppingCardRequest>(() => new ShoppingCardRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ShoppingCardRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QiLieGuaner.MsgMallReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShoppingCardRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShoppingCardRequest(ShoppingCardRequest other) : this() {
      playerGUID_ = other.playerGUID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShoppingCardRequest Clone() {
      return new ShoppingCardRequest(this);
    }

    /// <summary>Field number for the "playerGUID" field.</summary>
    public const int PlayerGUIDFieldNumber = 1;
    private int playerGUID_;
    /// <summary>
    ///玩家GUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerGUID {
      get { return playerGUID_; }
      set {
        playerGUID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ShoppingCardRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ShoppingCardRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerGUID != other.PlayerGUID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerGUID != 0) hash ^= PlayerGUID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerGUID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ShoppingCardRequest other) {
      if (other == null) {
        return;
      }
      if (other.PlayerGUID != 0) {
        PlayerGUID = other.PlayerGUID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///购物车列表响应
  /// </summary>
  public sealed partial class ShoppingCardReceive : pb::IMessage<ShoppingCardReceive>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ShoppingCardReceive> _parser = new pb::MessageParser<ShoppingCardReceive>(() => new ShoppingCardReceive());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ShoppingCardReceive> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QiLieGuaner.MsgMallReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShoppingCardReceive() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShoppingCardReceive(ShoppingCardReceive other) : this() {
      playerGUID_ = other.playerGUID_;
      result_ = other.result_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShoppingCardReceive Clone() {
      return new ShoppingCardReceive(this);
    }

    /// <summary>Field number for the "playerGUID" field.</summary>
    public const int PlayerGUIDFieldNumber = 1;
    private int playerGUID_;
    /// <summary>
    ///玩家GUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerGUID {
      get { return playerGUID_; }
      set {
        playerGUID_ = value;
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_result_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> result_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///商品信息。每项之间用‘|’分隔
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Result {
      get { return result_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ShoppingCardReceive);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ShoppingCardReceive other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerGUID != other.PlayerGUID) return false;
      if(!result_.Equals(other.result_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerGUID != 0) hash ^= PlayerGUID.GetHashCode();
      hash ^= result_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      result_.WriteTo(output, _repeated_result_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      result_.WriteTo(ref output, _repeated_result_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerGUID);
      }
      size += result_.CalculateSize(_repeated_result_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ShoppingCardReceive other) {
      if (other == null) {
        return;
      }
      if (other.PlayerGUID != 0) {
        PlayerGUID = other.PlayerGUID;
      }
      result_.Add(other.result_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 18: {
            result_.AddEntriesFrom(input, _repeated_result_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 18: {
            result_.AddEntriesFrom(ref input, _repeated_result_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///更新购物车商品数量请求
  /// </summary>
  public sealed partial class UpdateShoppingCardGoodsAmountRequest : pb::IMessage<UpdateShoppingCardGoodsAmountRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateShoppingCardGoodsAmountRequest> _parser = new pb::MessageParser<UpdateShoppingCardGoodsAmountRequest>(() => new UpdateShoppingCardGoodsAmountRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateShoppingCardGoodsAmountRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QiLieGuaner.MsgMallReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateShoppingCardGoodsAmountRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateShoppingCardGoodsAmountRequest(UpdateShoppingCardGoodsAmountRequest other) : this() {
      playerGUID_ = other.playerGUID_;
      updateType_ = other.updateType_;
      goodsID_ = other.goodsID_;
      goodsAddAmount_ = other.goodsAddAmount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateShoppingCardGoodsAmountRequest Clone() {
      return new UpdateShoppingCardGoodsAmountRequest(this);
    }

    /// <summary>Field number for the "playerGUID" field.</summary>
    public const int PlayerGUIDFieldNumber = 1;
    private int playerGUID_;
    /// <summary>
    ///玩家GUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerGUID {
      get { return playerGUID_; }
      set {
        playerGUID_ = value;
      }
    }

    /// <summary>Field number for the "updateType" field.</summary>
    public const int UpdateTypeFieldNumber = 2;
    private global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest.Types.UpdateAmountType updateType_ = global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest.Types.UpdateAmountType.Increase;
    /// <summary>
    ///更新数量是增加还是减少
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest.Types.UpdateAmountType UpdateType {
      get { return updateType_; }
      set {
        updateType_ = value;
      }
    }

    /// <summary>Field number for the "goodsID" field.</summary>
    public const int GoodsIDFieldNumber = 3;
    private int goodsID_;
    /// <summary>
    ///商品ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoodsID {
      get { return goodsID_; }
      set {
        goodsID_ = value;
      }
    }

    /// <summary>Field number for the "goodsAddAmount" field.</summary>
    public const int GoodsAddAmountFieldNumber = 4;
    private int goodsAddAmount_;
    /// <summary>
    ///商品增加的数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoodsAddAmount {
      get { return goodsAddAmount_; }
      set {
        goodsAddAmount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateShoppingCardGoodsAmountRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateShoppingCardGoodsAmountRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerGUID != other.PlayerGUID) return false;
      if (UpdateType != other.UpdateType) return false;
      if (GoodsID != other.GoodsID) return false;
      if (GoodsAddAmount != other.GoodsAddAmount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerGUID != 0) hash ^= PlayerGUID.GetHashCode();
      if (UpdateType != global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest.Types.UpdateAmountType.Increase) hash ^= UpdateType.GetHashCode();
      if (GoodsID != 0) hash ^= GoodsID.GetHashCode();
      if (GoodsAddAmount != 0) hash ^= GoodsAddAmount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (UpdateType != global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest.Types.UpdateAmountType.Increase) {
        output.WriteRawTag(16);
        output.WriteEnum((int) UpdateType);
      }
      if (GoodsID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(GoodsID);
      }
      if (GoodsAddAmount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(GoodsAddAmount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (UpdateType != global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest.Types.UpdateAmountType.Increase) {
        output.WriteRawTag(16);
        output.WriteEnum((int) UpdateType);
      }
      if (GoodsID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(GoodsID);
      }
      if (GoodsAddAmount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(GoodsAddAmount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerGUID);
      }
      if (UpdateType != global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest.Types.UpdateAmountType.Increase) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UpdateType);
      }
      if (GoodsID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodsID);
      }
      if (GoodsAddAmount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodsAddAmount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateShoppingCardGoodsAmountRequest other) {
      if (other == null) {
        return;
      }
      if (other.PlayerGUID != 0) {
        PlayerGUID = other.PlayerGUID;
      }
      if (other.UpdateType != global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest.Types.UpdateAmountType.Increase) {
        UpdateType = other.UpdateType;
      }
      if (other.GoodsID != 0) {
        GoodsID = other.GoodsID;
      }
      if (other.GoodsAddAmount != 0) {
        GoodsAddAmount = other.GoodsAddAmount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            UpdateType = (global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest.Types.UpdateAmountType) input.ReadEnum();
            break;
          }
          case 24: {
            GoodsID = input.ReadInt32();
            break;
          }
          case 32: {
            GoodsAddAmount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            UpdateType = (global::QiLieGuaner.UpdateShoppingCardGoodsAmountRequest.Types.UpdateAmountType) input.ReadEnum();
            break;
          }
          case 24: {
            GoodsID = input.ReadInt32();
            break;
          }
          case 32: {
            GoodsAddAmount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the UpdateShoppingCardGoodsAmountRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      ///更新数量类型，增加或者减少
      /// </summary>
      public enum UpdateAmountType {
        /// <summary>
        ///增加数量
        /// </summary>
        [pbr::OriginalName("Increase")] Increase = 0,
        /// <summary>
        ///减少数量
        /// </summary>
        [pbr::OriginalName("Reduce")] Reduce = 1,
      }

    }
    #endregion

  }

  /// <summary>
  ///更新购物车商品数量响应
  /// </summary>
  public sealed partial class UpdateShoppingCardGoodsAmountReceive : pb::IMessage<UpdateShoppingCardGoodsAmountReceive>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateShoppingCardGoodsAmountReceive> _parser = new pb::MessageParser<UpdateShoppingCardGoodsAmountReceive>(() => new UpdateShoppingCardGoodsAmountReceive());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateShoppingCardGoodsAmountReceive> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QiLieGuaner.MsgMallReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateShoppingCardGoodsAmountReceive() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateShoppingCardGoodsAmountReceive(UpdateShoppingCardGoodsAmountReceive other) : this() {
      playerGUID_ = other.playerGUID_;
      goodsID_ = other.goodsID_;
      goodsAmount_ = other.goodsAmount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateShoppingCardGoodsAmountReceive Clone() {
      return new UpdateShoppingCardGoodsAmountReceive(this);
    }

    /// <summary>Field number for the "playerGUID" field.</summary>
    public const int PlayerGUIDFieldNumber = 1;
    private int playerGUID_;
    /// <summary>
    ///玩家GUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerGUID {
      get { return playerGUID_; }
      set {
        playerGUID_ = value;
      }
    }

    /// <summary>Field number for the "goodsID" field.</summary>
    public const int GoodsIDFieldNumber = 2;
    private int goodsID_;
    /// <summary>
    ///商品ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoodsID {
      get { return goodsID_; }
      set {
        goodsID_ = value;
      }
    }

    /// <summary>Field number for the "goodsAmount" field.</summary>
    public const int GoodsAmountFieldNumber = 3;
    private int goodsAmount_;
    /// <summary>
    ///商品当前的数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoodsAmount {
      get { return goodsAmount_; }
      set {
        goodsAmount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateShoppingCardGoodsAmountReceive);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateShoppingCardGoodsAmountReceive other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerGUID != other.PlayerGUID) return false;
      if (GoodsID != other.GoodsID) return false;
      if (GoodsAmount != other.GoodsAmount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerGUID != 0) hash ^= PlayerGUID.GetHashCode();
      if (GoodsID != 0) hash ^= GoodsID.GetHashCode();
      if (GoodsAmount != 0) hash ^= GoodsAmount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (GoodsID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoodsID);
      }
      if (GoodsAmount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(GoodsAmount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (GoodsID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoodsID);
      }
      if (GoodsAmount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(GoodsAmount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerGUID);
      }
      if (GoodsID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodsID);
      }
      if (GoodsAmount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodsAmount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateShoppingCardGoodsAmountReceive other) {
      if (other == null) {
        return;
      }
      if (other.PlayerGUID != 0) {
        PlayerGUID = other.PlayerGUID;
      }
      if (other.GoodsID != 0) {
        GoodsID = other.GoodsID;
      }
      if (other.GoodsAmount != 0) {
        GoodsAmount = other.GoodsAmount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            GoodsID = input.ReadInt32();
            break;
          }
          case 24: {
            GoodsAmount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            GoodsID = input.ReadInt32();
            break;
          }
          case 24: {
            GoodsAmount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///购物车结算请求
  /// </summary>
  public sealed partial class SettlementRequest : pb::IMessage<SettlementRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SettlementRequest> _parser = new pb::MessageParser<SettlementRequest>(() => new SettlementRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SettlementRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QiLieGuaner.MsgMallReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettlementRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettlementRequest(SettlementRequest other) : this() {
      playerGUID_ = other.playerGUID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettlementRequest Clone() {
      return new SettlementRequest(this);
    }

    /// <summary>Field number for the "playerGUID" field.</summary>
    public const int PlayerGUIDFieldNumber = 1;
    private int playerGUID_;
    /// <summary>
    ///玩家GUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerGUID {
      get { return playerGUID_; }
      set {
        playerGUID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SettlementRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SettlementRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerGUID != other.PlayerGUID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerGUID != 0) hash ^= PlayerGUID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerGUID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SettlementRequest other) {
      if (other == null) {
        return;
      }
      if (other.PlayerGUID != 0) {
        PlayerGUID = other.PlayerGUID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///购物车结算响应
  /// </summary>
  public sealed partial class SettlementReceive : pb::IMessage<SettlementReceive>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SettlementReceive> _parser = new pb::MessageParser<SettlementReceive>(() => new SettlementReceive());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SettlementReceive> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QiLieGuaner.MsgMallReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettlementReceive() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettlementReceive(SettlementReceive other) : this() {
      playerGUID_ = other.playerGUID_;
      state_ = other.state_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettlementReceive Clone() {
      return new SettlementReceive(this);
    }

    /// <summary>Field number for the "playerGUID" field.</summary>
    public const int PlayerGUIDFieldNumber = 1;
    private int playerGUID_;
    /// <summary>
    ///玩家GUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerGUID {
      get { return playerGUID_; }
      set {
        playerGUID_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 2;
    private int state_;
    /// <summary>
    ///结算结果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SettlementReceive);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SettlementReceive other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerGUID != other.PlayerGUID) return false;
      if (State != other.State) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerGUID != 0) hash ^= PlayerGUID.GetHashCode();
      if (State != 0) hash ^= State.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (State != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerGUID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PlayerGUID);
      }
      if (State != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerGUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerGUID);
      }
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(State);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SettlementReceive other) {
      if (other == null) {
        return;
      }
      if (other.PlayerGUID != 0) {
        PlayerGUID = other.PlayerGUID;
      }
      if (other.State != 0) {
        State = other.State;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            State = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerGUID = input.ReadInt32();
            break;
          }
          case 16: {
            State = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
